name: 'Publish Fierro-CPU'

on: 
  push:
    paths:
      - .conda/fierro/cpu/**
      - .github/workflows/publish-fierro-cpu.yaml
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/build-conda-package.yaml
    with:
      recipe_dir: .conda/fierro/cpu
    secrets: inherit
